spring.application.name=demo
#logging.level.root=INFO
#logging.level.com.hana8=DEBUG
#logging.file.name=logs/application.log
#logging.file.path=logs/
#logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java
