import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import { ThemeProvider } from 'next-themes';
import { ModeToggle } from '@/components/ModeToggle';
import UserProfile from '@/components/UserProfile';
import { Button } from '@/components/ui/button';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 제일 바깥족에 있으므로 -> root layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-5 antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="mb-5 border-b pb-5">
            <div>
              Navigator <Link href={'/hello'}>Hello</Link>|
              <Link href={'/hi'}>Hi</Link>|<Link href={'/shop/123'}>123</Link>|
              <Link href={'/shop/456'}>456</Link>|
              <Link href={'/intercept'}>Intercept</Link>|
              <Link href={'/photos'}>Photos</Link>|
              <Link href={'/caches'}>Caches</Link>|
              <Link href={'/board/edit'}>Board</Link>
              <Button variant={'apply'}>SignIn</Button>
            </div>
            <div>
              <ModeToggle />
              <UserProfile />
            </div>
          </nav>
          <div className="border p-3">{children}</div>

          <footer className="text-center">Footer</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
