import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// 제일 바깥족에 있으므로 -> root layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const x = 1;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-5 antialiased`}
      >
        <nav className="mb-5 border-b pb-5">
          Navigator <Link href={'/hello'}>Hello</Link>|
          <Link href={'/hi'}>Hi</Link>
          <Link href={'/shop/123'}>123</Link>
          <Link href={'/shop/456'}>456</Link>
        </nav>
        <div className="border p-3">{children}</div>
        <footer className="text-center">Footer</footer>
      </body>
    </html>
  );
}
